// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"BBS_VersionDisplay","status":true,"description":"v1.02 Adds display of the game version to the title screen.\r\nSpecial Thanks to Tsukihime for all the help.\r\nSpecial Thanks to 'Ramza' Michael Sweeney for all the support.\r\n\r\n============================================================================\r\nParameters\r\n============================================================================","parameters":{"Game Version Number":"1.3.3","Game Version Font":"","Version Font Size":"20","Show Version Number?":"true","Version Text Color":"orange","Version Outline Color":"black","Version Outline Width":"8","Title Italic":"false","Version Text Max Width":"Graphics.width / 3\r"}},
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"CrystalGemTitle","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"CTB_ExitCommand","status":true,"description":"v1.20 CT_Bolt's ExitCommand Plugin","parameters":{"Exit Game Text":"Thoát game","Add To Title Screen":"true","Add To GameEnd Screen":"true","titlePos":"","gameEndPos":""}},
{"name":"HIME_SideviewActorEnemies","status":true,"description":"v1.2 - Allows you to use side-view actors as enemies.","parameters":{}},
{"name":"loadCommand","status":true,"description":"","parameters":{}}
];
